//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VCad.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_VCADTYPE                    129
#define IDR_CREATE                      130
#define IDR_MODIFY                      132
#define IDR_VIEW                        134
#define IDR_PROPERTYBAR                 136
#define IDC_DRAW_LINE                   138
#define IDC_DRAW_ARC                    139
#define IDC_DRAW_RECT                   140
#define IDC_DRAW_CIRCLE                 141
#define IDC_PROMPT_ARC                  142
#define IDC_PROMPT_CIRCLE               143
#define IDC_PROMPT_LINE                 144
#define IDC_PROMPT_RECT                 145
#define IDC_PROMPT_ELLIPSE              146
#define IDC_DRAW_ELLIPSE                147
#define IDC_DRAW_TEXT                   148
#define IDC_DRAW_POLYGON                149
#define IDC_PROMPT_TEXT                 150
#define IDC_PROMPT_POLYGON              151
#define IDD_TEXT_INPUT                  152
#define IDC_DRAW_CONNECT                154
#define IDC_PROMPT_CONNECT              155
#define IDC_PROMPT_BLOCK                156
#define IDC_DRAW_BLOCK                  157
#define IDD_DIALOG1                     158
#define IDD_DIALOG2                     159
#define IDD_DIALOG_CHENDEZHI            289
#define IDD_DIALOG_FLAW_ADD             290
#define IDC_EDIT1                       961
#define IDC_EDIT_R2                     962
#define IDC_EDIT4                       962
#define IDC_EDIT_H                      963
#define IDC_EDIT6                       963
#define IDC_EDIT9                       964
#define IDC_EDIT_CUR                    965
#define IDC_EDIT7                       965
#define IDC_EDIT_FREQ                   966
#define IDC_EDIT11                      966
#define IDC_EDIT_DIS                    967
#define IDC_EDIT12                      967
#define IDC_EDIT_TR1                    968
#define IDC_EDIT13                      968
#define IDC_EDIT_TR2                    969
#define IDC_EDIT14                      969
#define IDC_EDIT_TSIG                   970
#define IDC_EDIT15                      970
#define IDC_EDIT_TMIU                   971
#define IDC_EDIT16                      971
#define IDC_EDIT_TURN                   972
#define IDC_EDIT17                      972
#define IDC_EDIT_SR1                    973
#define IDC_EDIT18                      973
#define IDC_EDIT_SH                     974
#define IDC_EDIT19                      974
#define IDC_EDIT_SPOS                   975
#define IDC_EDIT20                      975
#define IDC_EDIT_SSIG                   976
#define IDC_EDIT_SMIU                   977
#define IDC_EDIT_STARTPOS               982
#define IDC_EDIT_STEP                   983
#define IDC_EDIT_SCANSTEPS              985
#define IDC_EDIT_TEXT                   1000
#define IDC_STATIC_FILEPREVIEW          1002
#define IDC_CHECK_PREVIEW               1003
#define IDC_CHECK1                      1109
#define IDC_EDIT2                       1142
#define IDC_EDIT5                       1143
#define IDC_EDIT3                       1143
#define IDC_EDIT8                       1144
#define IDC_EDIT10                      1145
#define IDC_BUTTON_DELALL               1305
#define IDC_EDIT_R1                     1306
#define IDC_LIST2                       1307
#define IDC_BUTTON_DEL                  1416
#define IDC_BUTTON1                     1430
#define IDC_BUTTON_ADD                  1433
#define IDC_BUTTON_ADD2                 1434
#define IDD_DIALOG_FILEPREVIEW          3557
#define ID_CREATE_LINE                  32760
#define ID_CREATE_RECTANGLE             32761
#define ID_CREATE_CIRCLE                32762
#define ID_CREATE_ARC                   32763
#define ID_CREATE_TEXT                  32764
#define ID_CREATE_ELLIPSE               32765
#define ID_CREATE_POLYGON               32766
#define ID_CREATE_BLOCK                 32767
#define ID_CREATE_CONNECT               32768
#define ID_PICK                         32776
#define IDM_SAVE_DXF                    32782
#define ID_CREATE_OTHER                 32783
#define ID_REDRAW                       32785
#define ID_PROPERTY                     32788
#define ID_VIEW_REGION                  32789
#define ID_VIEW_ZOOMIN                  32790
#define ID_VIEW_ZOOMOUT                 32791
#define ID_VIEW_ZOOMALL                 32792
#define ID_ZOOMOUT                      32792
#define ID_VIEW_MOVE                    32793
#define ID_VIEW_PAN                     32797
#define ID_EDIT_MANHADUN                32806
#define ID_MENUITEM32807                32807
#define ID_MENUITEM32808                32808
#define ID_MENUITEM32809                32809
#define ID_MENUITEM32810                32810
#define ID_MENUITEM32811                32811
#define ID_MENUITEM32812                32812
#define ID_MENUITEM32813                32813
#define ID_MENUITEM32814                32814
#define ID_MENUITEM32815                32815
#define ID_INNERPT                      32816
#define ID_CMD_COPY_BMP                 32817
#define IDW_LINECOLOR                   59143
#define IDW_LINEWIDTH                   59144
#define IDW_LINESTYLE                   59145
#define ID_MODIFY_MOVE                  61121
#define ID_MODIFY_ROTATE                61122
#define ID_MODIFY_MIRROR                61123
#define ID_MODIFY_ERASE                 61124

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
